baseURL = 'https://sadwhale.github.io/'
languageCode = 'en-us'
title = 'Sad Whale'
theme = 'hugo-xterm'

[params]
  centerTheme = true
  showMenuItems = true
  # favicon = "/images/xterm.png"
  showBreadCrumbs = true
  toc = true
  # copyrightUserUrl = "https://manid2.gitlab.io/"
  # copyrightUserText = "Mani Kumar"
